#!/bin/bash

echo "🧠 VoiceStand Learning System Dashboard"
echo "======================================"
echo ""
echo "🌐 Dashboard URL: http://localhost:7890"
echo "📚 API Documentation: http://localhost:7890/api/docs"
echo "📊 Real-time Metrics: http://localhost:7890/api/v1/metrics"
echo ""
echo "✅ Gateway Status:"
curl -s http://localhost:7890/health | python3 -m json.tool 2>/dev/null || echo "❌ Gateway not responding"
echo ""
echo "📈 Current Performance:"
curl -s http://localhost:7890/api/v1/metrics | python3 -m json.tool 2>/dev/null || echo "❌ Metrics not available"
echo ""
echo "🎯 To view the full dashboard:"
echo "   • Open your browser"
echo "   • Navigate to: http://localhost:7890"
echo "   • Or run: xdg-open http://localhost:7890 (Linux)"
echo ""
echo "🔧 Available API Endpoints:"
echo "   • GET  /health                    - Health check"
echo "   • GET  /api/v1/metrics            - Learning metrics"
echo "   • GET  /api/v1/models             - Model performance"
echo "   • POST /api/v1/recognition        - Submit recognition data"
echo "   • GET  /api/v1/insights           - Learning insights"
echo "   • GET  /api/v1/activity           - Recent activity"
echo "   • POST /api/v1/optimize           - Trigger optimization"
echo ""